/*!
 * @file  CreateDataObject.h
 * @brief データ型一覧
 *
 */

#ifndef CREATEDATAOBJECT_H
#define CREATEDATAOBJECT_H

#include <QMap>

namespace rtmiddleware {
	static const QMap<QString, QString> dataTypeList = {
		std::pair<QString, QString>(),
		std::pair<QString, QString>("RTC::ime","RTC.Time"),
		std::pair<QString, QString>("RTC::TimedState" , "RTC.TimedState"),
		std::pair<QString, QString>("RTC::TimedShort" ,"RTC.TimedShort"),
		std::pair<QString, QString>("RTC::TimedLong" ,"RTC.TimedLong"),
		std::pair<QString, QString>("RTC::TimedUShort" ,"RTC.TimedUShort"),
		std::pair<QString, QString>("RTC::TimedULong" ,"RTC.TimedULong"),
		std::pair<QString, QString>("RTC::TimedFloat" ,"RTC.TimedFloat"),
		std::pair<QString, QString>("RTC::TimedDouble" ,"RTC.TimedDouble"),
		std::pair<QString, QString>("RTC::TimedChar" ,"RTC.TimedChar"),
		std::pair<QString, QString>("RTC::TimedWChar" ,"RTC.TimedWChar"),
		std::pair<QString, QString>("RTC::TimedBoolean" ,"RTC.TimedBoolean"),
		std::pair<QString, QString>("RTC::TimedOctet" ,"RTC.TimedOctet"),
		std::pair<QString, QString>("RTC::TimedString" ,"RTC.TimedString"),
		std::pair<QString, QString>("RTC::TimedWString" ,"RTC.TimedWString"),
		std::pair<QString, QString>("RTC::TimedShortSeq" ,"RTC.TimedShortSeq"),
		std::pair<QString, QString>("RTC::TimedLongSeq" ,"RTC.TimedLongSeq"),
		std::pair<QString, QString>("RTC::TimedUShortSeq" ,"RTC.TimedUShortSeq"),
		std::pair<QString, QString>("RTC::TimedULongSeq" ,"RTC.TimedULongSeq"),
		std::pair<QString, QString>("RTC::TimedFloatSeq" ,"RTC.TimedFloatSeq"),
		std::pair<QString, QString>("RTC::TimedDoubleSeq" ,"RTC.TimedDoubleSeq"),
		std::pair<QString, QString>("RTC::TimedCharSeq" ,"RTC.TimedCharSeq"),
		std::pair<QString, QString>("RTC::TimedWCharSeq" ,"RTC.TimedWCharSeq"),
		std::pair<QString, QString>("RTC::TimedBooleanSeq" ,"RTC.TimedBooleanSeq"),
		std::pair<QString, QString>("RTC::TimedOctetSeq" ,"RTC.TimedOctetSeq"),
		std::pair<QString, QString>("RTC::TimedStringSeq" ,"RTC.TimedStringSeq"),
		std::pair<QString, QString>("RTC::TimedWStringSeq" ,"RTC.TimedWStringSeq"),
		std::pair<QString, QString>("RTC::RGBColour" ,"RTC.RGBColour"),
		std::pair<QString, QString>("RTC::Point2D" ,"RTC.Point2D"),
		std::pair<QString, QString>("RTC::Vector2D" ,"RTC.Vector2D"),
		std::pair<QString, QString>("RTC::Pose2D" ,"RTC.Pose2D"),
		std::pair<QString, QString>("RTC::Velocity2D" ,"RTC.Velocity2D"),
		std::pair<QString, QString>("RTC::Acceleration2D" ,"RTC.Acceleration2D"),
		std::pair<QString, QString>("RTC::PoseVel2D" ,"RTC.PoseVel2D"),
		std::pair<QString, QString>("RTC::Size2D" ,"RTC.Size2D"),
		std::pair<QString, QString>("RTC::Geometry2D" ,"RTC.Geometry2D"),
		std::pair<QString, QString>("RTC::Covariance2D" ,"RTC.Covariance2D"),
		std::pair<QString, QString>("RTC::PointCovariance2D" ,"RTC.PointCovariance2D"),
		std::pair<QString, QString>("RTC::Carlike" ,"RTC.Carlike"),
		std::pair<QString, QString>("RTC::SpeedHeading2D" ,"RTC.SpeedHeading2D"),
		std::pair<QString, QString>("RTC::Point3D" ,"RTC.Point3D"),
		std::pair<QString, QString>("RTC::Vector3D" ,"RTC.Vector3D"),
		std::pair<QString, QString>("RTC::Orientation3D" ,"RTC.Orientation3D"),
		std::pair<QString, QString>("RTC::Pose3D" ,"RTC.Pose3D"),
		std::pair<QString, QString>("RTC::Velocity3D" ,"RTC.Velocity3D"),
		std::pair<QString, QString>("RTC::AngularVelocity3D" ,"RTC.AngularVelocity3D"),
		std::pair<QString, QString>("RTC::Acceleration3D" ,"RTC.Acceleration3D"),
		std::pair<QString, QString>("RTC::AngularAcceleration3D" ,"RTC.AngularAcceleration3D"),
		std::pair<QString, QString>("RTC::PoseVel3D" ,"RTC.PoseVel3D"),
		std::pair<QString, QString>("RTC::Size3D" ,"RTC.Size3D"),
		std::pair<QString, QString>("RTC::Geometry3D" ,"RTC.Geometry3D"),
		std::pair<QString, QString>("RTC::Covariance3D" ,"RTC.Covariance3D"),
		std::pair<QString, QString>("RTC::SpeedHeading3D" ,"RTC.SpeedHeading3D"),
		std::pair<QString, QString>("RTC::OAP" ,"RTC.OAP"),
		std::pair<QString, QString>("RTC::TimedRGBColour" ,"RTC.TimedRGBColour"),
		std::pair<QString, QString>("RTC::TimedPoint2D" ,"RTC.TimedPoint2D"),
		std::pair<QString, QString>("RTC::TimedVector2D" ,"RTC.TimedVector2D"),
		std::pair<QString, QString>("RTC::TimedPose2D" ,"RTC.TimedPose2D"),
		std::pair<QString, QString>("RTC::TimedVelocity2D" ,"RTC.TimedVelocity2D"),
		std::pair<QString, QString>("RTC::TimedAcceleration2D" ,"RTC.TimedAcceleration2D"),
		std::pair<QString, QString>("RTC::TimedPoseVel2D" ,"RTC.TimedPoseVel2D"),
		std::pair<QString, QString>("RTC::TimedSize2D" ,"RTC.TimedSize2D"),
		std::pair<QString, QString>("RTC::TimedGeometry2D" ,"RTC.TimedGeometry2D"),
		std::pair<QString, QString>("RTC::TimedCovariance2D" ,"RTC.TimedCovariance2D"),
		std::pair<QString, QString>("RTC::TimedPointCovariance2D" ,"RTC.TimedPointCovariance2D"),
		std::pair<QString, QString>("RTC::TimedCarlike" ,"RTC.TimedCarlike"),
		std::pair<QString, QString>("RTC::TimedSpeedHeading2D" ,"RTC.TimedSpeedHeading2D"),
		std::pair<QString, QString>("RTC::TimedPoint3D" ,"RTC.TimedPoint3D"),
		std::pair<QString, QString>("RTC::TimedVector3D" ,"RTC.TimedVector3D"),
		std::pair<QString, QString>("RTC::TimedOrientation3D" ,"RTC.TimedOrientation3D"),
		std::pair<QString, QString>("RTC::TimedPose3D" ,"RTC.TimedPose3D"),
		std::pair<QString, QString>("RTC::TimedVelocity3D" ,"RTC.TimedVelocity3D"),
		std::pair<QString, QString>("RTC::TimedAngularVelocity3D" ,"RTC.TimedAngularVelocity3D"),
		std::pair<QString, QString>("RTC::TimedAcceleration3D" ,"RTC.TimedAcceleration3D"),
		std::pair<QString, QString>("RTC::TimedAngularAcceleration3D" ,"RTC.TimedAngularAcceleration3D"),
		std::pair<QString, QString>("RTC::TimedPoseVel3D" ,"RTC.TimedPoseVel3D"),
		std::pair<QString, QString>("RTC::TimedSize3D" ,"RTC.TimedSize3D"),
		std::pair<QString, QString>("RTC::TimedGeometry3D" ,"RTC.TimedGeometry3D"),
		std::pair<QString, QString>("RTC::TimedCovariance3D" ,"RTC.TimedCovariance3D"),
		std::pair<QString, QString>("RTC::TimedSpeedHeading3D" ,"RTC.TimedSpeedHeading3D"),
		std::pair<QString, QString>("RTC::TimedOAP" ,"RTC.TimedOAP"),
		std::pair<QString, QString>("RTC::Quaternion" ,"RTC.Quaternion"),
		std::pair<QString, QString>("RTC::TimedQuaternion" ,"RTC.TimedQuaternion"),
		std::pair<QString, QString>("RTC::ActArrayActuatorPos" ,"RTC.ActArrayActuatorPos"),
		std::pair<QString, QString>("RTC::ActArrayActuatorSpeed" ,"RTC.ActArrayActuatorSpeed"),
		std::pair<QString, QString>("RTC::ActArrayActuatorCurrent" ,"RTC.ActArrayActuatorCurrent"),
		std::pair<QString, QString>("RTC::Actuator" ,"RTC.Actuator"),
		std::pair<QString, QString>("RTC::ActArrayState" ,"RTC.ActArrayState"),
		std::pair<QString, QString>("RTC::ActArrayActuatorGeometry" ,"RTC.ActArrayActuatorGeometry"),
		std::pair<QString, QString>("RTC::ActArrayGeometry" ,"RTC.ActArrayGeometry"),
		std::pair<QString, QString>("RTC::BumperGeometry" ,"RTC.BumperGeometry"),
		std::pair<QString, QString>("RTC::BumperArrayGeometry" ,"RTC.BumperArrayGeometry"),
		std::pair<QString, QString>("RTC::CameraImage" ,"RTC.CameraImage"),
		std::pair<QString, QString>("RTC::CameraInfo" ,"RTC.CameraInfo"),
		std::pair<QString, QString>("RTC::FiducialInfo" ,"RTC.FiducialInfo"),
		std::pair<QString, QString>("RTC::Fiducials" ,"RTC.Fiducials"),
		std::pair<QString, QString>("RTC::FiducialFOV" ,"RTC.FiducialFOV"),
		std::pair<QString, QString>("RTC::GPSTime" ,"RTC.GPSTime"),
		std::pair<QString, QString>("RTC::GPSData" ,"RTC.GPSData"),
		std::pair<QString, QString>("RTC::GripperState" ,"RTC.GripperState"),
		std::pair<QString, QString>("RTC::INSData" , "RTC.INSData"),
		std::pair<QString, QString>("RTC::LimbState" , "RTC.LimbState"),
		std::pair<QString, QString>("RTC::Hypothesis2D" , "RTC.Hypothesis2D"),
		std::pair<QString, QString>("RTC::Hypotheses2D" , "RTC.Hypotheses2D"),
		std::pair<QString, QString>("RTC::Hypothesis3D" , "RTC.Hypothesis3D"),
		std::pair<QString, QString>("RTC::Hypotheses3D" , "RTC.Hypotheses3D"),
		std::pair<QString, QString>("RTC::OGMapConfig" , "RTC.OGMapConfig"),
		std::pair<QString, QString>("RTC::OGMapTile" , "RTC.OGMapTile"),
		std::pair<QString, QString>("RTC::PointFeature" , "RTC.PointFeature"),
		std::pair<QString, QString>("RTC::PoseFeature" , "RTC.PoseFeature"),
		std::pair<QString, QString>("RTC::LineFeature" , "RTC.LineFeature"),
		std::pair<QString, QString>("RTC::Features" , "RTC.Features"),
		std::pair<QString, QString>("RTC::MultiCameraImages" , "RTC.MultiCameraImages"),
		std::pair<QString, QString>("RTC::MulticameraGeometry" , "RTC.MulticameraGeometry"),
		std::pair<QString, QString>("RTC::Waypoint2D" , "RTC.Waypoint2D"),
		std::pair<QString, QString>("RTC::Path2D" , "RTC.Path2D"),
		std::pair<QString, QString>("RTC::Waypoint3D" , "RTC.Waypoint3D"),
		std::pair<QString, QString>("RTC::Path3D" , "RTC.Path3D"),
		std::pair<QString, QString>("RTC::PointCloudPoint" , "RTC.PointCloudPoint"),
		std::pair<QString, QString>("RTC::PointCloud" , "RTC.PointCloud"),
		std::pair<QString, QString>("RTC::PanTiltAngles" , "RTC.PanTiltAngles"),
		std::pair<QString, QString>("RTC::RangerGeometry" , "RTC.RangerGeometry"),
		std::pair<QString, QString>("RTC::RangerConfig" , "RTC.RangerConfig"),
		std::pair<QString, QString>("RTC::RangeData" , "RTC.RangeData"),
		std::pair<QString, QString>("RTC::IntensityData" , "RTC.IntensityData"),
		std::pair<QString, QString>("Img::ImageData" , "Img.ImageData"),
		std::pair<QString, QString>("Img::CameraIntrinsicParameter" , "Img.CameraIntrinsicParameter"),
		std::pair<QString, QString>("Img::CameraImage" , "Img.CameraImage"),
		std::pair<QString, QString>("Img::TimedCameraImage" , "Img.TimedCameraImage"),
		std::pair<QString, QString>("Img::MultiCameraImage" , "Img.MultiCameraImage"),
		std::pair<QString, QString>("Img::TimedMultiCameraImage" , "Img.TimedMultiCameraImage"),
		std::pair<QString, QString>("Img::NamedValue" , "Img.NamedValue"),
		std::pair<QString, QString>("Img::CameraDeviceProfile" , "Img.CameraDeviceProfile")
	};
}


#endif // CREATEDATAOBJECT_H
