// This file is generated by omniidl (C++ backend)- omniORB_4_3. Do not edit.
#ifndef __MessageView_hh__
#define __MessageView_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_MessageView
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_MessageView
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_MessageView
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE cnoid

_CORBA_MODULE_BEG

  _CORBA_MODULE Corba

  _CORBA_MODULE_BEG

#ifndef __cnoid_mCorba_mMessageView__
#define __cnoid_mCorba_mMessageView__
    class MessageView;
    class _objref_MessageView;
    class _impl_MessageView;
    
    typedef _objref_MessageView* MessageView_ptr;
    typedef MessageView_ptr MessageViewRef;

    class MessageView_Helper {
    public:
      typedef MessageView_ptr _ptr_type;

      static _ptr_type _nil();
      static _CORBA_Boolean is_nil(_ptr_type);
      static void release(_ptr_type);
      static void duplicate(_ptr_type);
      static void marshalObjRef(_ptr_type, cdrStream&);
      static _ptr_type unmarshalObjRef(cdrStream&);
    };

    typedef _CORBA_ObjRef_Var<_objref_MessageView, MessageView_Helper> MessageView_var;
    typedef _CORBA_ObjRef_OUT_arg<_objref_MessageView,MessageView_Helper > MessageView_out;

#endif

    // interface MessageView
    class MessageView {
    public:
      // Declarations for this interface type.
      typedef MessageView_ptr _ptr_type;
      typedef MessageView_var _var_type;

      static _ptr_type _duplicate(_ptr_type);
      static _ptr_type _narrow(::CORBA::Object_ptr);
      static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
      
      static _ptr_type _nil();

      static inline void _marshalObjRef(_ptr_type, cdrStream&);

      static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
        omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static inline _ptr_type _fromObjRef(omniObjRef* o) {
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static _core_attr const char* _PD_repoId;

      // Other IDL defined within this scope.
      
    };

    class _objref_MessageView :
      public virtual ::CORBA::Object,
      public virtual omniObjRef
    {
    public:
      // IDL operations
      void put(const char* message);

      // Constructors
      inline _objref_MessageView()  { _PR_setobj(0); }  // nil
      _objref_MessageView(omniIOR*, omniIdentity*);

    protected:
      virtual ~_objref_MessageView();

      
    private:
      virtual void* _ptrToObjRef(const char*);

      _objref_MessageView(const _objref_MessageView&);
      _objref_MessageView& operator = (const _objref_MessageView&);
      // not implemented

      friend class MessageView;
    };

    class _pof_MessageView : public _OMNI_NS(proxyObjectFactory) {
    public:
      inline _pof_MessageView() : _OMNI_NS(proxyObjectFactory)(MessageView::_PD_repoId) {}
      virtual ~_pof_MessageView();

      virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
      virtual _CORBA_Boolean is_a(const char*) const;
    };

    class _impl_MessageView :
      public virtual omniServant
    {
    public:
      virtual ~_impl_MessageView();

      virtual void put(const char* message) = 0;
      
    public:  // Really protected, workaround for xlC
      virtual _CORBA_Boolean _dispatch(omniCallHandle&);

    private:
      virtual void* _ptrToInterface(const char*);
      virtual const char* _mostDerivedRepoId();
      
    };


    _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_MessageView;

  _CORBA_MODULE_END

_CORBA_MODULE_END



_CORBA_MODULE POA_cnoid
_CORBA_MODULE_BEG

  _CORBA_MODULE Corba
  _CORBA_MODULE_BEG

    class MessageView :
      public virtual cnoid::Corba::_impl_MessageView,
      public virtual ::PortableServer::ServantBase
    {
    public:
      virtual ~MessageView();

      inline ::cnoid::Corba::MessageView_ptr _this() {
        return (::cnoid::Corba::MessageView_ptr) _do_this(::cnoid::Corba::MessageView::_PD_repoId);
      }
    };

  _CORBA_MODULE_END

_CORBA_MODULE_END



_CORBA_MODULE OBV_cnoid
_CORBA_MODULE_BEG

  _CORBA_MODULE Corba
  _CORBA_MODULE_BEG

  _CORBA_MODULE_END

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, cnoid::Corba::MessageView_ptr _s);
void operator<<=(::CORBA::Any& _a, cnoid::Corba::MessageView_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, cnoid::Corba::MessageView_ptr& _s);



inline void
cnoid::Corba::MessageView::_marshalObjRef(::cnoid::Corba::MessageView_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_MessageView
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_MessageView
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_MessageView
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_MessageView
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_MessageView
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_MessageView
#endif

#endif  // __MessageView_hh__

